[Settings]
ID = "CourseMaker Demo Site"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  command = "yarn build"
  # Ignore build command if exit 0
  ignore = "git diff --quiet HEAD^ HEAD sub_dir/"

  environment = {
  	GATSBY_AUTH0_DOMAIN="update me",
	GATSBY_AUTH0_CLIENTID="secret",
	GATSBY_AUTH0_CALLBACK="http://localhost:8000/callback",
	GATSBY_STRIPE_PUBLISHABLE_KEY="update me",
	GATSBY_BUTTON_PRICE_ID="update me",
	GATSBY_ENABLE_PAYMENTS=true
  }
