[Settings]
ID = "CourseMaker Demo Site"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  base = "/"
  command = "yarn build"
  publish = "/public"

[context.deploy-preview.environment]
  GATSBY_AUTH0_DOMAIN="update me"
  GATSBY_AUTH0_CLIENTID="secret"
  GATSBY_AUTH0_CALLBACK="http://localhost:8000/callback"
  GATSBY_STRIPE_PUBLISHABLE_KEY="update me"
  GATSBY_BUTTON_PRICE_ID="update me"
  GATSBY_ENABLE_PAYMENTS="true"
