version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  js-tests:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.5.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
          paths:
            - "@coursemaker/gatsby-theme-coursemaker/node_modules"
            - course_demo_site/node_modules
      - run:
          name: Run Front-End Test and Coverage
          command: |
            yarn test

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish